from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context
from alembic.script import ScriptDirectory

from app.config import settings
from app.database import Base
from app import models  # noqa: F401 — register models on Base.metadata

config = context.config
config.set_main_option("sqlalchemy.url", settings.database_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


# SQLite can't ALTER most columns, so Alembic must rewrite tables in "batch"
# mode for it. MySQL alters in place and doesn't need (or want) batch mode.
_is_sqlite = settings.database_url.startswith("sqlite")


def use_sequential_rev_ids(context_, revision, directives) -> None:
    """Give autogenerated migrations zero-padded sequential ids (0004, 0005, ...)
    instead of Alembic's default random hex, so `ls alembic/versions` reads in
    history order. Only runs during `revision --autogenerate`.
    """
    if not directives:
        return
    script = ScriptDirectory.from_config(context_.config)
    numbers = [int(rev.revision) for rev in script.walk_revisions() if rev.revision.isdigit()]
    directives[0].rev_id = f"{(max(numbers) + 1) if numbers else 1:04d}"


def run_migrations_offline() -> None:
    context.configure(
        url=settings.database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=_is_sqlite,
        process_revision_directives=use_sequential_rev_ids,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=_is_sqlite,
            process_revision_directives=use_sequential_rev_ids,
        )
        with context.begin_transaction():
            context.run_migrations()
    connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
